MdeModulePkg/UnicodeCollation: Fix uninitialized variable usage
Build failed with the below error:
error: variable 'Status' is used uninitialized whenever 'if'
condition is false.

Fixing this issue by initializing Status to EFI_SUCCESS
in the if condition false case.

This is a regression issue caused by below Edk2 commit
a46697f

Signed-off-by: HemaAnmisha <hema.anmisha.kalavakolanu@intel.com>